// Lossless PNG optimizer for built-in theme assets. Wraps the oxipng
// binary (bundled via the oxipng-bin dev dependency) which re-tries PNG
// filter strategies + optimal DEFLATE — strictly lossless, pixels are
// never altered, only the compressed stream is rewritten.
//
// Scope: assets/theme/**/*.png and assets/character/**/*.png only.
// assets/dist/ is the Nuxt SSG output (regenerated by `pnpm generate`)
// and is intentionally skipped. assets/f-theme uses webp, not png.
//
// Usage:
//   pnpm optimize:images             optimize in place (-o 2, strip safe)
//   pnpm optimize:images --check     dry-run, report savings only (exit 1 if shrinkable)
//   pnpm optimize:images --level 4   higher = slower but smaller (0-6, default 2)
//   pnpm optimize:images --verbose   show per-file oxipng output
//
// Iron Rule 4 (server-side re-encode on upload) is unaffected: this
// script only touches pre-built-in assets, not the upload channel.
import { spawn } from 'node:child_process';
import { readdir, stat } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), '..');
const OXIPNG = join(repoRoot, 'node_modules', '.bin', 'oxipng');

// Directories whose PNGs are source assets worth optimizing.
const SCAN_DIRS = ['assets/theme', 'assets/character'];

const args = process.argv.slice(2);
const checkOnly = args.includes('--check');
const verbose = args.includes('--verbose');
const levelIdx = args.indexOf('--level');
const level = levelIdx >= 0 && args[levelIdx + 1] ? Number(args[levelIdx + 1]) : 2;
if (!Number.isInteger(level) || level < 0 || level > 6) {
  console.error(`invalid --level: ${level} (expected 0-6)`);
  process.exit(2);
}

const collectPngs = async (dir) => {
  const out = [];
  let entries;
  try {
    entries = await readdir(dir, { withFileTypes: true });
  } catch {
    return out;
  }
  for (const e of entries) {
    const full = join(dir, e.name);
    if (e.isDirectory()) {
      out.push(...(await collectPngs(full)));
    } else if (e.isFile() && e.name.toLowerCase().endsWith('.png')) {
      out.push(full);
    }
  }
  return out;
};

const totalSize = async (files) => {
  let sum = 0;
  for (const f of files) {
    const s = await stat(f);
    sum += s.size;
  }
  return sum;
};

// Run oxipng on a batch. In check mode uses --pretend (no writes) and
// parses the "N bytes decrease" lines to sum potential savings. Returns
// the parsed total bytes that could be saved.
const runOxipng = (files, { check }) => new Promise((resolve, reject) => {
  const cliArgs = ['-o', String(level), '--strip', 'safe'];
  if (check) cliArgs.push('--pretend');
  cliArgs.push(...files);
  const child = spawn(OXIPNG, cliArgs, { stdio: verbose ? 'inherit' : 'pipe' });
  let stdout = '';
  if (!verbose && child.stderr) {
    child.stderr.on('data', (d) => { stdout += d.toString(); });
  }
  child.on('error', reject);
  child.on('exit', (code) => {
    if (code === 0) resolve(stdout);
    else reject(new Error(`oxipng exited ${code}`));
  });
});

// Sum "X bytes decrease" from oxipng --pretend output.
const sumDecrease = (output) => {
  let total = 0;
  for (const m of output.matchAll(/(\d+) bytes decrease/g)) {
    total += Number(m[1]);
  }
  return total;
};

const main = async () => {
  const files = [];
  for (const d of SCAN_DIRS) {
    files.push(...(await collectPngs(join(repoRoot, d))));
  }
  if (files.length === 0) {
    console.log('no PNG files found to optimize');
    return;
  }

  const before = await totalSize(files);
  const mode = checkOnly ? 'check (dry-run)' : 'optimize';
  console.log(`${mode}: ${files.length} PNG files, ${(before / 1024 / 1024).toFixed(1)} MiB total, oxipng -o ${level}`);

  if (checkOnly) {
    const out = await runOxipng(files, { check: true });
    const decrease = sumDecrease(out);
    if (decrease > 0) {
      console.log(`shrinkable: ~${(decrease / 1024).toFixed(0)} KiB (${(decrease * 100 / before).toFixed(1)}%) could be saved`);
      console.log('run `pnpm optimize:images` to apply');
      process.exit(1);
    }
    console.log('all PNGs already optimal; nothing to do');
    return;
  }

  await runOxipng(files, { check: false });
  const after = await totalSize(files);
  const saved = before - after;
  const pct = before > 0 ? (saved * 100 / before).toFixed(2) : '0.00';
  console.log(`done: ${(before / 1024 / 1024).toFixed(1)} MiB -> ${(after / 1024 / 1024).toFixed(1)} MiB (${(saved / 1024).toFixed(0)} KiB, ${pct}% smaller)`);
};

main().catch((err) => {
  console.error('optimize-images failed:', err.message);
  process.exit(1);
});
